# Generated by Django 6.0.2 on 2026-03-12 09:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('feed', 'Feed'), ('medication', 'Medication'), ('equipment', 'Equipment'), ('labor', 'Labor'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to='accounts.farm')),
            ],
        ),
    ]
