# Generated by Django 6.0.2 on 2026-03-12 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('feed', 'Feed'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('other', 'Other')], default='feed', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Weight in KG or unit count', max_digits=10)),
                ('unit', models.CharField(default='KG', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='accounts.farm')),
            ],
            options={
                'unique_together': {('name', 'farm')},
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Restock'), ('remove', 'Usage')], default='add', max_length=10)),
                ('quantity_changed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_at_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.inventoryitem')),
            ],
        ),
    ]
